services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_flask
    volumes:
      - ./api/api.py:/app/api.py
      - ./api/sql:/app/sql
    env_file:
      - ./api/.env
    ports:
      - "4201:4201"
    restart: always
    networks:
      - internal

  front:
    build:
      context: ./TFD-front
      dockerfile: Dockerfile
    container_name: front_dev
    ports:
      - "4202:80"
    volumes:
      - ./TFD-front:/app
      - /app/node_modules
    networks:
      - internal

networks:
  internal:
    driver: bridge