services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api_flask
    ports:
      - "4201:4201"
    expose:
      - "4201"
    environment:
      - ENV=production
    restart: always