services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api_flask
    ports:
      - "4201:4201"
    environment:
      - ENV=production
    restart: always

  front:
    build: ./TFD-front
    container_name: front
    restart: unless-stopped
    ports:
      - "80:80"