services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    environment:
      - API_URL=https://theory-crafter-api.pazimor.dev
    restart: unless-stopped
    ports:
      - "82:80"
