services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    environment:
      - API_URL=https://theory-crafter.pazimor.dev:4201
    restart: unless-stopped
    ports:
      - "81:80"
      - "444:443"
